### ISSUE TITLE
vmdk thin type support

### ISSUE THREAD

**Issue by bk1te** [vmware/vsphere-flocker-driver#20]
Currently only thick diskFormat volumes are supported is there any plans to add support for thin disks?

**Comment by pratikvgupta** [comment]
Currently, we are using thick provisioning as default as Flocker's only gives size as the input param for create_volume method.
There should be a way for clients to give other params via the flocker API as well instead of giving a  backdoor way to configure different params.

**Comment by jm66** [comment]
Hi @pratikvgupta, as per my understanding Flocker is not really aware whether the disk is  ```think``` or ```thin```provisioned (is it @wallnerryan? ), since the OS presents the disk.  I was also wondering about this param because most of our VMs are using ```thin``` provisioning using ```thick``` certainly reduces free storage in a datastore.

**Comment by pratikvgupta** [comment]
@jm66 Shall we change thick to thin by default?

**Comment by bk1te** [comment]
Is it possible to pass flocker metadata fields to vsphere driver. If so we could use them to define disk type. Using thin by default is preferable over thick disk types!

**Comment by wallnerryan** [comment]
Hi all,

You can use flocker profiles to allow users to get a set of defined attributes.

https://docs.clusterhq.com/en/latest/flocker-features/storage-profiles.html

Soon, we will have custom profiles, allowing more flexible mix and match of metadata attributes. 

By default, I usually recommend thin FWIW.

-Ryan

**Comment by jm66** [comment]
Thanks all. Thin by default should be fine :+1:  and the possibility to change the default from the config file?

**Comment by wallnerryan** [comment]
'the possibility to change the default from the config file?' you could but would need to added to a driver. Profiles are a better way to do this as you can get different values during runtime, rather than statically defining them before starting the daemon.

**Comment by bk1te** [comment]
@wallnerryan maybe you could provide an example how this could be done vsphere flocker driver?

**Comment by wallnerryan** [comment]
@bk1te Sure! 
Drivers that can take advantage of profiles need to implement [IProfilesBlockDeviceAPI](https://github.com/ClusterHQ/flocker/blob/master/flocker/node/agents/blockdevice.py#L1254). This provides all flocker drivers with `gold` `silver` and `bronze` profiles. What those designations "actually" mean is up to you. What does vmware consider `gold`? ...fast thin and protected? Maybe. Also your not limited to the 3 profiles, all the logic is there to add more than the 3 mandatory ones, but we havent made it easy to create `custom profiles` yet, we are working on that and if your interested I can get an update for you.

As an example, profiles [for Amazon EBS[(https://github.com/ClusterHQ/flocker/blob/master/flocker/node/agents/ebs.py#L156) we designated Gold, Silver, Bronze based on amazons 3 main EBS types.

```python
class EBSMandatoryProfileAttributes(Values):
    """
    These constants are the ``EBSProfileAttributes`` for the mandatory
    profiles. Many of the values for these were gotten from the documentation
    at:
    http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html
    :ivar GOLD: The high performing Provisioned IOPS disks.
    :ivar SILVER: The medium performing SSD disks.
    :ivar BRONZE: The cheap magnetic disks.
    """
    GOLD = ValueConstant(EBSProfileAttributes(volume_type=EBSVolumeTypes.IO1,
                                              iops_per_size_gib=30,
                                              max_iops=20000))
    # ``gp2`` volume type cannot take IOPS request since it defaults to
    # baseline performance of 3 IOPS/GiB (up to 10,000 IOPS)
    SILVER = ValueConstant(EBSProfileAttributes(
        volume_type=EBSVolumeTypes.GP2))
    BRONZE = ValueConstant(EBSProfileAttributes(
        volume_type=EBSVolumeTypes.STANDARD))
```

You can do that same for vmware. Say you wanted your GOLD profiles to set attributes of `thin-provision` and from `SSD`. If you have the capability, your able to provide it as an attribute in a profile.

**Comment by jm66** [comment]
Hi @wallnerryan @bk1te, 

Looks like the way Amazon EBS is handling profiles is to offer better performance, right? If we'd like to manage storage performance in profiles, using ```vSphere Storage Profiles``` would be best, but this would be a new feature in the driver (not sure if possible, @pratikvgupta?)

I believe provisioning configuration is not fully related to performance, but it's to how you want to handle your ```datastore``` space allocation. ```Thick``` or ```Thin``` is about how disks are created at vSphere layer and not necessarily one will have higher IOPs than the other. On the other hand, virtual machine ```SCSI``` controllers could offer better throughput depending on what you choose, for instance ```VMware Paravirtual SCSI``` has potentially less CPU cost per IO than ```LSI```. At the end, performance is given by the backend storage either ```NFS```, ```FC```,  or whether it has ```VAAI``` capabilities.

**Comment by wallnerryan** [comment]
@jm66 yes, typically profiles are used for use-cases that have to do with performance. But attributes can range thats why I mentioned it. It is very possible to set static configuration outside the driver implementation from the pool that the driver points at or even as an attribute in the config file (also would need a driver change). Again, I just wanted to make the options visible to this thread :)

**Comment by pratikvgupta** [comment]
Yes. Storage policy based management is the right way to enable such use-cases.
For a short term we can enable thin provisioning by default.

**Comment by bk1te** [comment]
Thanks!
