### ISSUE TITLE
vsphere-flocker-driver

### ISSUE THREAD

**Issue by catdrich** [vmware/vsphere-flocker-driver#3]
We are trying to use the vsphere-flocker-driver and are having some issues.  I've been working with the people at ClusterHQ, and they suggested I open something up here.  

The indications from flocker are that the volumes I try to create are in pending status:

docker volume create --name=testflockervolume --driver=flocker testflockervolume

docker volume inspect testflockervolume
[
    {
        "Name": "testflockervolume",
        "Driver": "flocker",
        "Mountpoint": ""
    }
]

Any volumes I have tried to create are in pending status (I tried to create apples and oranges - the postgres-volume-example shouldn't be there, but it was from an old attempt and we deleted the volume from the data share):
 uft-flocker-volumes --control-service=10.248.58.93 --user=plugin list
DATASET                                SIZE         METADATA                       STATUS        SERVER
91b07b31-69d8-47cb-ade9-40142187c8df   75.00G       name=oranges                   pending ⌛   6b07522a (10.248.58.93)
daeccf0a-d3c1-4c8c-8015-205c332f5b42   75.00G       name=apples                    pending ⌛   6b07522a (10.248.58.93)
2b0d59c7-0317-49e8-8c8e-5118b6ec7694   75.00G       name=vol1                      detached      6b07522a (10.248.58.93)
41f0b794-ddd1-4cdc-9adc-aab962ac9402   75.00G       name=testflockervolume         pending ⌛   6b07522a (10.248.58.93)
0df95ac0-4c36-4596-8fcf-4f6755959908   <no quota>   name=postgres-volume-example   pending ⌛   6b07522a (10.248.58.93)

I attached all the logs here, including the flocker logs.  What are we missing in order to get this to work?

[flocker logs.zip](https://github.com/vmware/vsphere-flocker-driver/files/56707/flocker.logs.zip)

**Comment by ferrantim** [comment]
Hi, is there an update on this issue VMware?

**Comment by pratikvgupta** [comment]
I am looking into this.
We will get it resolved soon.

**Comment by pratikvgupta** [comment]
The issue #7 has been fixed which is same as the issue described here.
Can you please install the latest and try?
