### ISSUE TITLE
Is this repo still active ?

### ISSUE THREAD

**Issue by mfilotto** [vmware/vsphere-flocker-driver#38]
Hi,
I would like to use this Flocker driver but I'm not sure it is maintained.
Thanks for your answer

**Comment by pdhamdhere** [comment]
@mfilotto Flocker driver is deprecated and vSphere now natively supports Docker Volumes using [vSphere Docker Volume Service](https://vmware.github.io/docker-volume-vsphere/). Let us know if you need quick walkthrough and we can jump on quick webex. Feel free to reach out to us @ containers@vmware.com
