### ISSUE TITLE
_list_vsphere_volumes and vim.VirtualApp

### ISSUE THREAD

**Issue by jm66** [vmware/vsphere-flocker-driver#5]
Looks like the code doesn't validad for the existence of vm.config.hardware and when vim.VirtualApp is found the code exits.

```
2016-01-22 11:38:48,723 - ERROR - List volumes failed with error: 'vim.ResourceConfigSpec' object has no attribute 'hardware'
```
I think the following validation would be good to have within the ```vms``` loop in ```_list_vsphere_volumes```:

```python
if isinstance(vm, vim.VirtualMachine) and hasattr(vm.config, 'hardware')
```

**Comment by ferrantim** [comment]
Hi @pratikvgupta could you take a look at this issue and PR?  Thanks!
